import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/main/AppSidebar";
import { Header } from "@/components/main/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <SidebarProvider>
        <AppSidebar />
        <main className="w-screen pt-14 flex">
          <SidebarTrigger className="h-screen items-start border-r border-input rounded-none py-7 px-9 fixed" />
          {children}
        </main>
      </SidebarProvider>
    </>
  );
}
